"""Stage the web bundle for the Android shell, then hand it to Capacitor.

The APK does not run a Python server, so every URL the page asks for has to
exist as a FILE in the same place the server would have answered it. That is
the whole job of this script, and getting it wrong is the classic native bug:
the app works in a browser and shows a white screen in the shell because
`/static/app.js` resolved to nothing.

The server's URL space is:

    /                       web/index.html
    /sw.js                  web/sw.js          (root, or its scope is /static)
    /manifest.webmanifest   web/manifest.webmanifest
    /offline.html           web/offline.html
    /favicon.ico            web/favicon.ico
    /static/*               web/*

so dist/ is built to match it exactly, character for character. There is no
second layout to keep in sync and no relative-path rewrite that works in one
build and not the other.

    py -V:3.13 scripts/android_build.py --api-base http://10.0.2.2:8744
    py -V:3.13 scripts/android_build.py --api-base https://api.example.com --release
"""
from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
WEB = ROOT / "web"
DIST = ROOT / "dist"

# Served from the root by explicit routes in graticule/server.py. The service
# worker is the one that MUST be here: a worker's scope is the directory it was
# served from, so a /static/sw.js could never see the navigation to "/".
ROOT_FILES = ["index.html", "sw.js", "manifest.webmanifest", "offline.html", "favicon.ico"]


def stage(api_base: str) -> None:
    # The engine and satellite.js live in web/vendor and are copied along with
    # everything else below. They used to come off cesium.com and jsdelivr at
    # runtime, which made two CDNs hard dependencies of an offline-capable app.
    # Checked HERE rather than only in static_checks because this is the last
    # point before the bytes go into an APK: a version bumped in package.json
    # with the committed copy left behind would ship silently otherwise.
    vendored = subprocess.run(
        [sys.executable, str(Path(__file__).resolve().parent / "vendor_assets.py"),
         "--check"], capture_output=True, text=True)
    if vendored.returncode != 0:
        print(vendored.stdout.strip())
        raise SystemExit("web/vendor is out of step with node_modules; "
                         "run: py -V:3.13 scripts/vendor_assets.py")

    if DIST.exists():
        shutil.rmtree(DIST)
    (DIST / "static").mkdir(parents=True)

    # Everything under /static, which is the whole of web/ including data/.
    # Bundling the prebuilt GeoJSON rather than fetching it means the borders,
    # coastlines and counties are on disk at first paint instead of 13 MB over
    # a mobile connection, and they keep working with no signal.
    shutil.copytree(WEB, DIST / "static", dirs_exist_ok=True)

    for name in ROOT_FILES:
        src = WEB / name
        if not src.exists():
            raise SystemExit(f"missing {src} -- the shell would 404 on /{name}")
        shutil.copy2(src, DIST / name)

    cfg = DIST / "static" / "api-config.js"
    cfg.write_text(
        "/* GENERATED by scripts/android_build.py -- do not edit.\n"
        " * The web build keeps web/api-config.js with an empty base. */\n"
        f"window.GRATICULE_API_BASE = {json.dumps(api_base)};\n",
        encoding="utf-8",
    )

    size = sum(f.stat().st_size for f in DIST.rglob("*") if f.is_file())
    print(f"staged {DIST}  ({size / 1_048_576:.1f} MB uncompressed)")
    # An empty base used to be a mistake worth shouting about: the shell would
    # ask https://localhost for /api and get nothing. It is now the correct
    # and intended value. The feeds run in the page (web/feeds.js), so a
    # native build has no backend to name, and naming one would only send the
    # app looking for something that does not need to exist.
    print(f"  API base: {api_base or '(none -- the feeds run on the device)'}")
    if api_base:
        print("  NOTE: a base is set, so ?api= can be used to exercise the old "
              "server path. The shipped build does not need it.")


def run(cmd: list[str], **kw) -> None:
    print("$", " ".join(cmd))
    subprocess.run(cmd, cwd=ROOT, check=True, shell=(sys.platform == "win32"), **kw)


# Capacitor 7 compiles against source release 21. The JDK on PATH here is 17,
# which fails with a message that names neither Capacitor nor the requirement:
# "error: invalid source release: 21". Android Studio ships a bundled JDK 21
# and that is the one Android Studio itself would use, so the command line
# should agree with the IDE rather than depend on whatever `java` resolves to.
JDK_CANDIDATES = [
    Path(r"C:\Program Files\Android\Android Studio\jbr"),
    Path(r"C:\Program Files\Android\openjdk\jdk-21.0.8"),
]


def find_jdk21() -> Path | None:
    for base in JDK_CANDIDATES:
        exe = base / "bin" / ("java.exe" if sys.platform == "win32" else "java")
        if not exe.exists():
            continue
        try:
            out = subprocess.run([str(exe), "-version"], capture_output=True, text=True)
            banner = (out.stderr or "") + (out.stdout or "")
        except OSError:
            continue
        # `version "21` and not `version "21x`: matching a bare "21" would also
        # accept 2.1 and 210 if either ever existed.
        if 'version "21' in banner:
            return base
    return None


def gradle_env() -> dict[str, str]:
    import os
    env = dict(os.environ)
    jdk = find_jdk21()
    if jdk:
        env["JAVA_HOME"] = str(jdk)
        print(f"JAVA_HOME -> {jdk}")
    else:
        print("WARNING: no JDK 21 found. Capacitor 7 needs one and the build "
              "will fail with 'invalid source release: 21'.")
    # ANDROID_HOME on this machine is the literal string ':LOCALAPPDATA\\Android\\Sdk'
    # -- an unexpanded variable that points nowhere. android/local.properties
    # carries the real path, so clear the broken one rather than let Gradle
    # prefer it.
    sdk = env.get("ANDROID_HOME", "")
    if sdk and not Path(sdk).is_dir():
        print(f"ignoring unusable ANDROID_HOME={sdk!r}; using android/local.properties")
        env.pop("ANDROID_HOME", None)
        env.pop("ANDROID_SDK_ROOT", None)
    return env


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--api-base", default="",
                    help="Origin the APK talks to. 10.0.2.2 is the emulator's host.")
    ap.add_argument("--stage-only", action="store_true")
    ap.add_argument("--release", action="store_true",
                    help="assembleRelease instead of assembleDebug")
    # Play takes an App Bundle, not an APK. An APK is still what you install on
    # a device by hand, so both exist rather than one replacing the other.
    ap.add_argument("--aab", action="store_true",
                    help="bundleRelease: the .aab Play actually wants (implies --release)")
    args = ap.parse_args()

    if args.aab:
        args.release = True

    # A release build may not talk to a plain-http backend. capacitor.config.js
    # would silently drop the page to http://localhost to keep mixed-content
    # blocking off, and that is a development affordance -- shipping it would
    # put every user's radar and location requests on the open wire.
    #
    # An EMPTY base is not that, and is now the shipping shape: the feeds run
    # in the page, so there is no backend to be plain-http about. This guard
    # used to demand an https base on every release, which would have refused
    # the only build that should ever go to Play. It dates from when a backend
    # was mandatory and was not revisited when that stopped being true.
    if args.release and args.api_base and not args.api_base.startswith("https://"):
        raise SystemExit(
            f"refusing to build a release against {args.api_base!r}.\n"
            "Name an https backend, or leave --api-base empty, which is the\n"
            "shipped shape: the feeds run on the device. See capacitor.config.js.")

    stage(args.api_base)
    if args.stage_only:
        return

    import os
    sync_env = dict(os.environ, GRATICULE_API_BASE=args.api_base)
    print("$ npx cap sync android")
    subprocess.run(["npx", "cap", "sync", "android"], cwd=ROOT, check=True,
                   shell=(sys.platform == "win32"), env=sync_env)

    # A release build with no keystore.properties compiles happily and produces
    # an UNSIGNED artifact that Play rejects at upload. Saying so here costs
    # nothing and saves finding out at the end of a submission.
    if args.release and not (ROOT / "android" / "keystore.properties").exists():
        print("\n  ** android/keystore.properties is missing. This build will be")
        print("     UNSIGNED and Play will reject it. See keystore.properties.example. **\n")

    gradle = "gradlew.bat" if sys.platform == "win32" else "./gradlew"
    if args.aab:
        task = "bundleRelease"
    elif args.release:
        task = "assembleRelease"
    else:
        task = "assembleDebug"
    subprocess.run([gradle, task, "--console=plain"], cwd=ROOT / "android", check=True,
                   shell=(sys.platform == "win32"), env=gradle_env())

    kind = "release" if args.release else "debug"
    out = ROOT / "android" / "app" / "build" / "outputs"
    for f in sorted((out / "apk" / kind).glob("*.apk")):
        print(f"APK  {f}  ({f.stat().st_size / 1_048_576:.1f} MB)")
    if args.aab:
        for f in sorted((out / "bundle" / kind).glob("*.aab")):
            print(f"AAB  {f}  ({f.stat().st_size / 1_048_576:.1f} MB)")


if __name__ == "__main__":
    main()
